### ISSUE TITLE
welcome image code

### ISSUE THREAD

**Issue by aeiousy** [Tomato6966/Ask-Me-Anything#1]
hey I just want to know if you can add the code for the welcome image video alot of people were asking for it so now that you have a github mabe can you add it?

**Comment by Tomato6966** [comment]
Hey! Ofc I can! I will make the Code Clearer then I will add it!

**Comment by Tomato6966** [comment]
Done see it here! It works, and its even improved ;) https://github.com/Tomato6966/Discord-Welcome-Images
