### ISSUE TITLE
Ranking System issue

### ISSUE THREAD

**Issue by testbot123-cmd** [Tomato6966/Ask-Me-Anything#11]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Tomato6966/)! [I](https://github.com/Tomato6966/) will try my best to answer to you and help you!

- [☑️] Check that your question [was not already answered](https://github.com/Tomato6966/Ask-Me-Anything/issues?q=is%3Aissue+is%3Aclosed) please.
-----------------------------------------------------------------------------------------------------------------------------------

If I use replit and uptimerobot, when the bot goes offline then comes online it will not save the levels
and to save the levels we need to use a command to save it so please fix it.

**Comment by Tomato6966** [comment]
this is a problem from replit, because they delete the database files

**Comment by testbot123-cmd** [comment]
Can you fix it please @Tomato6966

**Comment by Tomato6966** [comment]
I cant, buy a vps and it will work
