### ISSUE TITLE
Copyright Issue

### ISSUE THREAD

**Issue by EmojiPati** [Tomato6966/Ask-Me-Anything#4]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Tomato6966/)! [I](https://github.com/Tomato6966/) will try my best to answer to you and help you!

- [x] Check that your question [was not already answered](https://github.com/Tomato6966/Ask-Me-Anything/issues?q=is%3Aissue+is%3Aclosed) please.
hi You removed the bot named music-bot-with-filter, I wonder I have a problem.
If you don't mind, can you help me for the filter part I was taking a sample from the repo, but you removed the repo
Can you help me please and how are you how is life going?

**Comment by Tomato6966** [comment]
my life is going stress full i am having 8 tests in the next 11 days so rip but sure ask me

**Comment by EmojiPati** [comment]
Anyway, I read the documents, I got something out for you, good luck in your exams
