### ISSUE TITLE
Ranking system , Is it possible that i could change rank card colors individual? like bar color or name color etc? Thank in advance.

### ISSUE THREAD

**Issue by AhmedYounes01** [Tomato6966/Ask-Me-Anything#7]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Tomato6966/)! [I](https://github.com/Tomato6966/) will try my best to answer to you and help you!

- [ ] Check that your question [was not already answered](https://github.com/Tomato6966/Ask-Me-Anything/issues?q=is%3Aissue+is%3Aclosed) please.

**Comment by Tomato6966** [comment]
Yeah just look in the code at rank or look up the docs of canvacord...

**Comment by Tomato6966** [comment]
If u need coding help join my support server https://support.milrato.eu

**Comment by AhmedYounes01** [comment]
Thanks alot i managed to do it :)

**Comment by AhmedYounes01** [comment]
It's awesome word u doing there my friend 💯
