### ISSUE TITLE
Decode pure anti nuke bot

### ISSUE THREAD

**Issue by PegBeenLaxkin** [Tomato6966/Ask-Me-Anything#9]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Tomato6966/)! [I](https://github.com/Tomato6966/) will try my best to answer to you and help you!

- [ ] Check that your question [was not already answered](https://github.com/Tomato6966/Ask-Me-Anything/issues?q=is%3Aissue+is%3Aclosed) please.

**Comment by Tomato6966** [comment]
What`?
